# OUTPUT_DIR: "Log/retrival_e2e_without_centerness" #0.8292275405326702 70000 step
# OUTPUT_DIR: "Log/ic15_bbox"
# OUTPUT_DIR: "Log/retrival_e2e_fix_bug" #0.8343403728936134 90000 step 
# OUTPUT_DIR: "Log/retrival_e2e_without_centerness_fix_bug" #0.8407678613834894 90000 step 
# OUTPUT_DIR: "Log/retrival_e2e_without_centerness_cls_fix_bug" #0.8454673095098002 90000 step 
# OUTPUT_DIR: "Log/retrival4" #0.8564087611385056 90000 step    0.8541520106433798 70000 step
# OUTPUT_DIR: "Log/retrival_e2e_without_centerness_cls_fix_bug" #0.8454673095098002 90000 step 
# OUTPUT_DIR: "Log/retrival_e2e_add_retrieval_loss" #0.8694 90000 step 
# OUTPUT_DIR: "Log/retrival_e2e_add_retrieval_loss_10" #0.8805036674399561 90000 step 
OUTPUT_DIR: "Log/retrival_e2e_synth_svt" #0.8657557852210778 90000 step 
# OUTPUT_DIR: "Log/retrival_e2e_synth_svt2" #0.8657557852210778 90000 step 

MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "./Log/retrival4/model_0070000.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50"
  NECK:
    CONV_BODY: "fpn-align"
  # RETINANET:
  #   USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2 # 0 for bg, 1 for text
    # NMS_TH: 0.3
  ALIGN:
    NUM_CONVS: 2
    POOLER_RESOLUTION: (4, 15)
    # POOLER_RESOLUTION: (32, 128)
    POOLER_SCALES: (0.25, 0.125, 0.0625) #must be aligned to feature maps 0.25 = feature_maps[0]/img_size
DATASETS:
  TRAIN: ("svt_train",)
  TEST: ("svt_test",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30000,60000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 2500

TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
