
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "model_iit_rec_domainalign_cc_7042.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-BN"
  # RESNETS:
  #   RES2_OUT_CHANNELS: 64
  NECK:
    CONV_BODY: "fpn-align-r18" # is the same with fpn-align
    NUM_LEVELS: 4
  # RETINANET:
  #   USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2 # 0 for bg, 1 for text
    # NMS_TH: 0.3
    USE_POLY: True
  ALIGN:
    USE_SCALENET: True
    USE_CTC_LOSS: False
    USE_NO_RNN: False
    USE_DOMAIN_ALIGN_LOSS: True
    USE_WORD_AUG: True
    NUM_CONVS: 2
    POOLER_RESOLUTION: (4, 15)
    # POOLER_RESOLUTION: (32, 128)
    POOLER_SCALES: (0.25, 0.125, 0.0625) #must be aligned to feature maps 0.25 = feature_maps[0]/img_size
DATASETS:
  # TRAIN: ("synthtext90k","verisimilar")
  TRAIN: ("synthtext90k",)
  # TRAIN: ("synthtext150k",)
  # TRAIN: ("totaltext_train",)
  # TEST: ("svt_test",)
  TEST: ("iiit_test",)
  # TEST: ("svt_test","iiit_test","cocotext_test")
  # TEST: ("cocotext_test",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
# SOLVER:
#   BASE_LR: 0.01
#   WEIGHT_DECAY: 0.0001
#   STEPS: (30000,60000)
#   MAX_ITER: 90000
#   IMS_PER_BATCH: 4 # 64 will OOM
#   CHECKPOINT_PERIOD: 10000
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (40,80)
  MAX_ITER: 200
  IMS_PER_BATCH: 4 # 64 will OOM
  CHECKPOINT_PERIOD: 100


TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  # AUGMENT: "SythAugmentation"
  AUGMENT: "PSSAugmentation"
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
