
# OUTPUT_DIR: "Log/finetune_on_ic17_sn_r18_l4" #960 79.84 24.13; 768 79.39 27.15; 640 77.37 31.00
# OUTPUT_DIR: "Log/finetune_on_ic17_sn_r18_l4_b16" #960 79.78
# OUTPUT_DIR: "Log/finetune_on_ic17_sn_r18_l4_norc" #960 
# OUTPUT_DIR: "Log/finetune_on_norec_ic17_sn_r18_l4_norc" #960 
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "./model_r18_l4_norec.pth"
  
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-18"
  RESNETS:
    RES2_OUT_CHANNELS: 64
  NECK:
    CONV_BODY: "fpn-align"
    NUM_LEVELS: 4
  # RETINANET:
  #   USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2 # 0 for bg, 1 for text
    # NMS_TH: 0.3
    USE_POLY: True
  ALIGN:
    USE_SCALENET: True
    USE_CTC_LOSS: False
    USE_NO_RNN: False
    USE_DOMAIN_ALIGN_LOSS: True
    USE_WORD_AUG: True
    NUM_CONVS: 2
    POOLER_RESOLUTION: (4, 15)
    # POOLER_RESOLUTION: (32, 128)
    POOLER_SCALES: (0.25, 0.125, 0.0625) #must be aligned to feature maps 0.25 = feature_maps[0]/img_size
    DET_SCORE: (0.2, 0.2, 0.05, 0.2)
DATASETS:
  # TRAIN: ("icdar15_train","icdar13_train")
  TRAIN: ("icdar17_train",)
  # TRAIN: ("icdar15_train",)
  # TRAIN: ("icdar13_train",)
  # TRAIN: ("verisimilar",)
  # TEST: ("svt_test",)
  # TEST: ("iiit_test",)
  # TEST: ("cocotext_test",)
  TEST: ("iiit_test","cocotext_test","svt_test","totaltext_test")
  # TEST: ("chinese_collect",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (40000,)
  MAX_ITER: 80000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 2500
# SOLVER:
#   BASE_LR: 0.0001
#   WEIGHT_DECAY: 0.0001
#   WARMUP_ITERS: 0
#   STEPS: (40000,)
#   MAX_ITER: 80000
#   IMS_PER_BATCH: 16
#   CHECKPOINT_PERIOD: 2500
# SOLVER:
#   BASE_LR: 0.0001
#   WEIGHT_DECAY: 0.0001
#   STEPS: (20000,)
#   MAX_ITER: 40000
#   IMS_PER_BATCH: 16
#   CHECKPOINT_PERIOD: 2500
# SOLVER:
#   BASE_LR: 0.0001
#   WEIGHT_DECAY: 0.0001
#   STEPS: (20000,)
#   MAX_ITER: 40000
#   IMS_PER_BATCH: 32
#   CHECKPOINT_PERIOD: 2500
# SOLVER:
#   BASE_LR: 0.0001
#   WEIGHT_DECAY: 0.0001
#   STEPS: (60000,)
#   MAX_ITER: 70000
#   IMS_PER_BATCH: 16
#   CHECKPOINT_PERIOD: 2500

TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  AUGMENT: "PSSAugmentation"
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
