OUTPUT_DIR: "Log/only_retrieval" #1280 0.8289499652578318
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RETRIEVAL_ONLY: True
  BACKBONE:
    CONV_BODY: "R-50"
DATASETS:
  TRAIN: ("synthtext90k_crop",)
  # TRAIN: ("icdar15_train",)
  # TRAIN: ("icdar17_train",)
  TEST: ("icdar2015_test",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
# SOLVER:
#   BASE_LR: 0.001
#   WEIGHT_DECAY: 0.0001
#   STEPS: (30000,)
#   MAX_ITER: 60000
#   IMS_PER_BATCH: 8
#   CHECKPOINT_PERIOD: 5000
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30000,60000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 128
  CHECKPOINT_PERIOD: 2500
TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  AUGMENT: "SythAugmentation"
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
