
OUTPUT_DIR: "Log/retrival_synthtext_chinese_1019"
# OUTPUT_DIR: "Log/draw"
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "./model_chinese.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50"
  NECK:
    CONV_BODY: "fpn-align"
  # RETINANET:
  #   USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2 # 0 for bg, 1 for text
    # NMS_TH: 0.3
  ALIGN:
    IS_CHINESE: True
    USE_ALONG_LOSS: False
    USE_N_GRAM_ED: False
    USE_COMMON_SPACE: False
    USE_HANMING: False
    USE_STEP: False
    USE_CHAR_COUNT: False
    USE_CONTRASTIVE_LOSS: False
    USE_TEXTNESS: False
    USE_IOU_PREDICTOR: False
    USE_WORD_AUG: True
    NUM_CONVS: 2
    POOLER_RESOLUTION: (4, 15)
    # POOLER_RESOLUTION: (32, 128)
    POOLER_SCALES: (0.25, 0.125, 0.0625) #must be aligned to feature maps 0.25 = feature_maps[0]/img_size
DATASETS:
  TRAIN: ("synthtext_chinese",)
  # TRAIN: ("ctw_train","rctw_train")
  # TEST: ("ctw_test",)
  TEST: ("chinese_collect",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30000,60000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 2500
# SOLVER:
#   BASE_LR: 0.0001
#   WEIGHT_DECAY: 0.0001
#   STEPS: (60000,)
#   MAX_ITER: 70000
#   IMS_PER_BATCH: 16
#   CHECKPOINT_PERIOD: 2500

TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  AUGMENT: "SythAugmentation"
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
