# OUTPUT_DIR: "Log/ic15_bbox"
OUTPUT_DIR: "Log/synthtext90k"
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "./model_final.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50"
  NECK:
    CONV_BODY: "fpn-align"
  # RETINANET:
  #   USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2 # 0 for bg, 1 for text
    # NMS_TH: 0.3
DATASETS:
  TRAIN: ("synthtext90k",)
  TEST: ("icdar15_test",)
# INPUT:
#   MIN_SIZE_RANGE_TRAIN: (640, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (70000,140000)
  MAX_ITER: 240000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 20000


INPUT:
  # MIN_SIZE_TEST: 480
  # MAX_SIZE_TEST: 768

  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]

  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5